### ISSUE TITLE
Drone failing because of `bbr::param_estimates_compare()`

### ISSUE THREAD

**Issue by graceannobrien** [metrumresearchgroup/pmparams#30] opened 2024-05-06 21:51 UTC
Drone failing because of `bbr::param_estimates_compare()` in `define_boot_table`:

Local bbr:
`bbr::param_estimates_compare()` outputs `p50` etc.

Drone bbr:
`bbr::param_estimates_compare()` output `50%` etc.

**Comment by seth127** [comment] 2024-05-07 13:55
Oops, this is a nuance we hadn't considered about our package management strategy for local development vs. CI. Here is my current understanding of the issue.

* We use `pkgr` for local development. For MetrumRG-developed packages, we pull the latest tag (e.g. for [here for bbr](https://github.com/metrumresearchgroup/pmparams/blob/main/pkgr.yml#L12)). 
  * Importantly, pulling the latest tag means we also get unreleased development tags.
  * The breakage here is caused by [this change](https://github.com/metrumresearchgroup/bbr/compare/main...1.10.0.8003#diff-439c4ab334a64029ab6198e6f3ce085b3d886d74b6a762fef92ee97f390c7f1d) being pulled in via the [1.10.0.8003 tag](https://github.com/metrumresearchgroup/bbr/releases/tag/1.10.0.8003)
* In CI (currently Drone) we pull dependencies from the latest MPN snapshot (or CRAN)
  *  This obviously only pulls versions that are _actually released_
* Because we have the unreleased changes (in this case, for `bbr`) locally, there were some breaking changes to the test data. In order to get the tests to pass locally, @graceannobrien made [this commit](https://github.com/metrumresearchgroup/pmparams/pull/21/commits/374e782c89c4bc6af94df2fc66a0e4c0edb4344e) which updates the test data.
* Unfortunately, this caused Drone to fail because it does not have the updated (unreleased) `bbr`, and therefore expected the old test data format.

I'm going to mull over the best solution for this going forward, and post another comment once I feel like I have an idea worth sharing. Anyone else is welcome to chime in too. 

**Key Questions:**

* Do we really want to be using unreleased tags of our dependencies for local development? I see pros and cons either way.
* If no, what's the best way to get the most recent _released_ versions via `pkgr`?
* If yes, do we also want to pull those same unreleased versions into CI?
  * If yes, what's the best approach for doing this?
  * If no, we will need to deal with situations like this that arise from having mismatches between the local and CI environments.

**Comment by seth127** [comment] 2024-05-07 14:09
I should also note that we're in the process of switching all our R package CI over to GitHub Actions (e.g. [nmrec PR](https://github.com/metrumresearchgroup/nmrec/pull/38)), so we don't need to agonize over any Drone-specific solution, if there's an easier solution there. 

In terms of dependencies, we're essentially doing the same thing of pulling them from the [most recent MPN](https://github.com/metrumresearchgroup/nmrec/blob/9ebdda8471a3768e9349b8102d9f655ed0aa195a/.github/workflows/main.yaml#L62).

**Comment by kyleam** [comment] 2024-05-07 14:13
[ Just my two cents... ]

> Do we really want to be using unreleased tags of our dependencies for local development? I see pros and cons either way.

It really depends on how those dev tags are being used.  Obviously in general it's good to be aware of the failures sooner, but in some of our projects dev tags tend to be used for long-term/intrusive changes that haven't yet settled.  There's not much point in chasing the problems until things are in a stable state.

In general, if a package is strongly coupled to another one (e.g., bbr.bayes with bbr), I suggest having the CI have a build testing against that dependency's `main` branch.  That will help catch incompatibilities fairly early.  Either way, I think the thought should be making the CI catch the cases we want, not the local development (which can only ever be in on state and is bound to grow stale).

In most cases, I'd follow what we do in most our packages for `pkgr.yml`: setit to the latest MPN URL at the time and then leave that be until an update is needed.

> If no, what's the best way to get the most recent _released_ versions via `pkgr`?

The local state is regularly going to be stale (e.g., if a dev hasn't ran `pkgr install` recently).  Again, I'd focus on making the CI catch the cases you really care about.  And then of course our common release procedure tests again the latest MPN, but it of course isn't a bad idea to run `score-r-pkg --allow-untagged ...` every now and then.


> If yes, do we also want to pull those same unreleased versions into CI?

As I mentioned above, I think it makes sense to have a dedicated build for the main branch of tightly coupled dependencies.

> If no, we will need to deal with situations like this that arise from having mismatches between the local and CI environments.

There will always be a mismatch.  Again, I'd just focus on the CI having the cases you care about.

**Comment by seth127** [comment] 2024-05-07 14:51
Thanks for chiming in @kyleam . Good points.

> The local state is regularly going to be stale (e.g., if a dev hasn't ran `pkgr install` recently)...

This is a fair point. I don't love putting snapshot dates in the `pkgr.yml` because that increases the chances of a stale dev environment even more. But we do have to accept that a stale dev environment is going to be a reality at times. And, on the other side, developers can intentionally install unreleased versions of dependencies locally, if they have some particular thing they want to test against.

>  I'd just focus on the CI having the cases you care about...

I agree. And we build against CRAN and the latest MPN (for our packages) in CI, so that's the most important point. If the dev environment is stale, and CI catches something, then that will remind the developer to make the relevant updates.

> In general, if a package is strongly coupled to another one (e.g., bbr.bayes with bbr), I suggest having the CI have a build testing against that dependency's main branch.

This makes sense as well, and will obviously be handled on a case-by-case basis. In the case of `pmparams`, this isn't necessary.

**Comment by seth127** [comment] 2024-05-07 15:00
So my proposed resolution for `pmparams` would be:

* [ ] Change `pkgr.yml` to pull from CRAN and `https://mpn.metworx.com/snapshots/stable/2024-03-01` (in that order)
  * [ ] Delete `bbr` from `renv/library/` and re-run `pkgr install`
  * [ ] Re-run the test suite locally --> the same tests currently failing on Drone should now fail locally
* [ ] Change the test data back to its original state (e.g. revert [this commit](https://github.com/metrumresearchgroup/pmparams/pull/21/commits/374e782c89c4bc6af94df2fc66a0e4c0edb4344e), and maybe others that I didn't notice)
* [ ] Push this change and Drone should now pass

I think at that point we'd be good for now. Whenever those `bbr` changes eventually get to MPN (likely in a few months), we'll need to make this change again, but that will be the correct time to make the update. At that point, we'll have to bump the MPN snapshot date in the `pkgr.yml` and then re-do the same test data change that cause the failure here.

**Comment by kyleam** [comment] 2024-05-07 15:11
@seth127 LGTM

> I think at that point we'd be good for now. Whenever those bbr changes eventually get to MPN (likely in a few months) [...]

That sounds fine.   The worst case scenario is that both of these changes are going into MPN at same time, and then I don't notice the failures until build time.  How to handle that kind of depends on the specifics, but assuming it's not just a pure test expectation issue, we'd need to either address it with a new release before cutting MPN or pin something.

>  At that point, we'll have to bump the MPN snapshot date in the pkgr.yml and then re-do the same test data change that cause the failure here.

And I guess also bump the bbr dependency, unless it's just a test expectation thing.  Another option would to be to make the code compatible with both versions of bbr.  Anyway, I agree that it probably makes sense to at least wait to address this until this lands in bbr's main.

---

In terms of getting the open PRs into a good state, I think the easiest way would be to make the proposed changes in a dedicated PR, and then once that is merged to main, merge main to each of the PRs.  (You could of course also rebase those PRs onto the new main.)

**Closed** 2024-05-09 16:12 UTC
